name: clean_architecture_tdd_flutter
description: Number trivia app with clean architecture and tdd.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: 2.5.2

dependencies:
  connectivity: ^3.0.6
  dartz: ^0.10.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  get_it: ^7.2.0
  http: ^0.13.4
  shared_preferences: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16

flutter:
  uses-material-design: true
